plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

version = "1.0.0"
group = "org.zeith.cloudflared.standalone"
archivesBaseName = "standalone-cloudflared-client"

sourceCompatibility = targetCompatibility = 1.8

repositories {
    mavenCentral()
    maven {
        name = "Zeitheron Maven"
        url = "https://maven.zeith.org"
    }
}

dependencies {
    implementation 'org.apache.logging.log4j:log4j-api:2.23.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.23.1' 
    
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    compileOnly 'org.jetbrains:annotations:24.0.1'
}

shadowJar {
    archiveBaseName.set(project.archivesBaseName)
    archiveClassifier.set('')
    archiveVersion.set(project.version)
    manifest {
        attributes 'Main-Class': 'org.zeith.cloudflared.core.StandaloneClientMain'
    }
}

jar {
    enabled = false
}

build {
    dependsOn shadowJar
}